// Auto-generated Architecture data - DO NOT EDIT MANUALLY
// Generated by: npm run docs:regenerate-data

import { DocMetadata } from './doc-types';

export const architectures: DocMetadata[] = [
  {
    "number": "001",
    "title": "Accessibility Reference",
    "category": "architecture",
    "majorCategory": "ACCESSIBILITY",
    "status": "Active",
    "date": "2026-01-14",
    "lastUpdated": "2026-01-14",
    "exportName": "ArchAccessibility001AccessibilityReference",
    "markdownPath": "/docs/architecture/ARCH-accessibility-001-accessibility-reference.md"
  },
  {
    "number": "001",
    "title": "Component Css Architecture",
    "category": "architecture",
    "majorCategory": "COMPONENTS",
    "status": "Mandatory",
    "date": "2026-01-14",
    "lastUpdated": "2026-01-14",
    "exportName": "ArchComponents001ComponentCssArchitecture",
    "markdownPath": "/docs/architecture/ARCH-components-001-component-css-architecture.md"
  },
  {
    "number": "002",
    "title": "Component Naming Conventions",
    "category": "architecture",
    "majorCategory": "COMPONENTS",
    "status": "Guide (Advisory)",
    "date": "2025-01-21",
    "lastUpdated": "2026-01-14",
    "exportName": "ArchComponents002ComponentNamingConventions",
    "markdownPath": "/docs/architecture/ARCH-components-002-component-naming-conventions.md"
  },
  {
    "number": "003",
    "title": "Componentfeature Architecture",
    "category": "architecture",
    "majorCategory": "COMPONENTS",
    "status": "Active",
    "date": "2026-01-14",
    "lastUpdated": "2026-01-14",
    "exportName": "ArchComponents003ComponentfeatureArchitecture",
    "markdownPath": "/docs/architecture/ARCH-components-003-componentfeature-architecture.md"
  },
  {
    "number": "001",
    "title": "Layout Composition Guide",
    "category": "architecture",
    "majorCategory": "LAYOUT",
    "status": "Guide (Advisory)",
    "date": "2026-01-06",
    "lastUpdated": "2026-01-14",
    "exportName": "ArchLayout001LayoutCompositionGuide",
    "markdownPath": "/docs/architecture/ARCH-layout-001-layout-composition-guide.md"
  },
  {
    "number": "001",
    "title": "Architecture Documentation",
    "category": "architecture",
    "majorCategory": "SYSTEM",
    "status": "Active",
    "date": "2026-01-14",
    "lastUpdated": "2026-01-14",
    "exportName": "ArchSystem001ArchitectureDocumentation",
    "markdownPath": "/docs/architecture/ARCH-system-001-architecture-documentation.md"
  },
  {
    "number": "002",
    "title": "Architecture Documentation Guide",
    "category": "architecture",
    "majorCategory": "SYSTEM",
    "status": "Active",
    "date": "2026-01-14",
    "lastUpdated": "2026-01-14",
    "exportName": "ArchSystem002ArchitectureDocumentationGuide",
    "markdownPath": "/docs/architecture/ARCH-system-002-architecture-documentation-guide.md"
  },
  {
    "number": "003",
    "title": "Architecture Validation Through Implementation",
    "category": "architecture",
    "majorCategory": "SYSTEM",
    "status": "Mandatory",
    "date": "2026-01-09",
    "lastUpdated": "2026-01-14",
    "owner": "Eugene Goncharov",
    "exportName": "ArchSystem003ArchitectureValidationThroughImplementation",
    "markdownPath": "/docs/architecture/ARCH-system-003-architecture-validation-through-implementation.md"
  },
  {
    "number": "004",
    "title": "Dev App Architecture",
    "category": "architecture",
    "majorCategory": "SYSTEM",
    "status": "Active",
    "date": "2026-01-14",
    "lastUpdated": "2026-01-14",
    "exportName": "ArchSystem004DevAppArchitecture",
    "markdownPath": "/docs/architecture/ARCH-system-004-dev-app-architecture.md"
  },
  {
    "number": "005",
    "title": "Storybook Story Structure Standard",
    "category": "architecture",
    "majorCategory": "SYSTEM",
    "status": "Active",
    "date": "2026-01-14",
    "lastUpdated": "2026-01-14",
    "exportName": "ArchSystem005StorybookStoryStructureStandard",
    "markdownPath": "/docs/architecture/ARCH-system-005-storybook-story-structure-standard.md"
  },
  {
    "number": "006",
    "title": "System Prefix",
    "category": "architecture",
    "majorCategory": "SYSTEM",
    "status": "Active",
    "date": "2026-01-14",
    "lastUpdated": "2026-01-14",
    "exportName": "ArchSystem006SystemPrefix",
    "markdownPath": "/docs/architecture/ARCH-system-006-system-prefix.md"
  },
  {
    "number": "001",
    "title": "Hero Section Theme Architecture",
    "category": "architecture",
    "majorCategory": "THEME",
    "status": "Active",
    "date": "2026-01-14",
    "lastUpdated": "2026-01-14",
    "exportName": "ArchTheme001HeroSectionThemeArchitecture",
    "markdownPath": "/docs/architecture/ARCH-theme-001-hero-section-theme-architecture.md"
  },
  {
    "number": "002",
    "title": "Theme Structure Analysis Composition Vs Semantic Breakdown",
    "category": "architecture",
    "majorCategory": "THEME",
    "status": "Active",
    "date": "2026-01-09",
    "lastUpdated": "2026-01-09",
    "exportName": "ArchTheme002ThemeStructureAnalysisCompositionVsSemanticBreakdown",
    "markdownPath": "/docs/architecture/ARCH-theme-002-theme-structure-analysis-composition-vs-semantic-breakdown.md"
  },
  {
    "number": "001",
    "title": "Color System Architecture Rules",
    "category": "architecture",
    "majorCategory": "TOKENS",
    "status": "Active",
    "date": "2026-01-14",
    "lastUpdated": "2026-01-14",
    "exportName": "ArchTokens001ColorSystemArchitectureRules",
    "markdownPath": "/docs/architecture/ARCH-tokens-001-color-system-architecture-rules.md"
  },
  {
    "number": "002",
    "title": "Css Token Output Rules",
    "category": "architecture",
    "majorCategory": "TOKENS",
    "status": "Active",
    "date": "2026-01-14",
    "lastUpdated": "2026-01-14",
    "exportName": "ArchTokens002CssTokenOutputRules",
    "markdownPath": "/docs/architecture/ARCH-tokens-002-css-token-output-rules.md"
  },
  {
    "number": "003",
    "title": "Token Architecture",
    "category": "architecture",
    "majorCategory": "TOKENS",
    "status": "Active",
    "date": "2026-01-14",
    "lastUpdated": "2026-01-14",
    "exportName": "ArchTokens003TokenArchitecture",
    "markdownPath": "/docs/architecture/ARCH-tokens-003-token-architecture.md"
  },
  {
    "number": "004",
    "title": "Token Usage Rules",
    "category": "architecture",
    "majorCategory": "TOKENS",
    "status": "Active",
    "date": "2026-01-14",
    "lastUpdated": "2026-01-14",
    "exportName": "ArchTokens004TokenUsageRules",
    "markdownPath": "/docs/architecture/ARCH-tokens-004-token-usage-rules.md"
  }
];
