// Auto-generated Tokens data - DO NOT EDIT MANUALLY
// Generated by: npm run docs:regenerate-data

import { DocMetadata } from './doc-types';

export const tokens: DocMetadata[] = [
  {
    number: "001",
    title: "Token System Tooling",
    category: "token",
    status: "Active",
    date: "2026-01-13",
    lastUpdated: "2026-01-13",
    owner: "Eugene Goncharov",
    assistance: "AI-assisted drafting (human-reviewed)",
    exportName: "tokenSystemTooling",
    markdownPath: "/docs/tokens/TOKENS-001-token-system-tooling.md",
    storybookId: "docs-tokens--token-system-tooling",
    aliases: ["tokens/README.md"]
  },
  {
    number: "002",
    title: "Token Reference",
    category: "token",
    status: "Active",
    date: "2026-01-13",
    lastUpdated: "2026-01-13",
    owner: "Eugene Goncharov",
    assistance: "AI-assisted drafting (human-reviewed)",
    exportName: "tokenReference",
    markdownPath: "/docs/tokens/TOKENS-002-token-reference.md",
    storybookId: "docs-tokens--token-reference",
    aliases: ["tokens/reference.md"]
  },
  {
    number: "003",
    title: "Token Utilities Use Cases",
    category: "token",
    status: "Active",
    date: "2026-01-13",
    lastUpdated: "2026-01-13",
    owner: "Eugene Goncharov",
    assistance: "AI-assisted drafting (human-reviewed)",
    exportName: "tokenUtilitiesUseCases",
    markdownPath: "/docs/tokens/TOKENS-003-token-utilities-use-cases.md",
    storybookId: "docs-tokens--token-utilities-use-cases",
    aliases: ["tokens/use-cases.md"]
  }
];
