// Auto-generated Workflow data - DO NOT EDIT MANUALLY
// Generated by: npm run docs:regenerate-data

import { DocMetadata } from './doc-types';

export const workflows: DocMetadata[] = [
  {
    number: "001",
    title: "ADR Workflow",
    category: "workflow",
    status: "Active",
    date: "2026-01-15",
    lastUpdated: "2026-01-15",
    owner: "Eugene Goncharov",
    assistance: "AI-assisted drafting (human-reviewed)",
    exportName: "adrWorkflow",
    markdownPath: "/docs/workflows/WORKFLOW-001-adr-workflow.md",
    storybookId: "docs-workflows--adr-workflow",
    aliases: ["workflows/adr-workflow.md"]
  },
  {
    number: "002",
    title: "Figma Workflow",
    category: "workflow",
    status: "Active",
    date: "2026-01-13",
    lastUpdated: "2026-01-15",
    owner: "Eugene Goncharov",
    assistance: "AI-assisted drafting (human-reviewed)",
    exportName: "figmaWorkflow",
    markdownPath: "/docs/workflows/WORKFLOW-002-figma-workflow.md",
    storybookId: "docs-workflows--figma-workflow",
    aliases: ["workflows/figma-workflow.md"]
  },
  {
    number: "003",
    title: "Storybook Workflow",
    category: "workflow",
    status: "Active",
    date: "2026-01-13",
    lastUpdated: "2026-01-13",
    owner: "Eugene Goncharov",
    assistance: "AI-assisted drafting (human-reviewed)",
    exportName: "storybookWorkflow",
    markdownPath: "/docs/workflows/WORKFLOW-003-storybook-workflow.md",
    storybookId: "docs-workflows--storybook-workflow",
    aliases: ["workflows/storybook-workflow.md"]
  },
  {
    number: "004",
    title: "Scripts Reference",
    category: "workflow",
    status: "Active",
    date: "2026-01-15",
    lastUpdated: "2026-01-15",
    owner: "Eugene Goncharov",
    assistance: "AI-assisted drafting (human-reviewed)",
    exportName: "scriptsReference",
    markdownPath: "/docs/workflows/WORKFLOW-004-scripts-reference.md",
    storybookId: "docs-workflows--scripts-reference",
    aliases: ["workflows/scripts-reference.md"]
  },
  {
    number: "005",
    title: "Tokens Workflow",
    category: "workflow",
    status: "Active",
    date: "2026-01-13",
    lastUpdated: "2026-01-13",
    owner: "Eugene Goncharov",
    assistance: "AI-assisted drafting (human-reviewed)",
    exportName: "tokensWorkflow",
    markdownPath: "/docs/workflows/WORKFLOW-005-tokens-workflow.md",
    storybookId: "docs-workflows--tokens-workflow",
    aliases: ["workflows/tokens-workflow.md"]
  },
  {
    number: "006",
    title: "Layer Generation Workflow",
    category: "workflow",
    status: "Active",
    date: "2026-01-12",
    lastUpdated: "2026-01-12",
    owner: "Eugene Goncharov",
    assistance: "AI-assisted drafting (human-reviewed)",
    exportName: "layerGenerationWorkflow",
    markdownPath: "/docs/workflows/WORKFLOW-006-layer-generation-workflow.md",
    storybookId: "docs-workflows--layer-generation-workflow",
    aliases: ["workflows/layer-generation-workflow.md"]
  },
  {
    number: "007",
    title: "Dev App Workflow",
    category: "workflow",
    status: "Active",
    date: "2026-01-13",
    lastUpdated: "2026-01-13",
    owner: "Eugene Goncharov",
    assistance: "AI-assisted drafting (human-reviewed)",
    exportName: "devAppWorkflow",
    markdownPath: "/docs/workflows/WORKFLOW-007-dev-app-workflow.md",
    storybookId: "docs-workflows--dev-app-workflow",
    aliases: ["workflows/dev-app-workflow.md"]
  }
];
